// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/molecules/button/Button.vue')['default']
    CharacterCard: typeof import('./components/molecules/character-card/CharacterCard.vue')['default']
    CharacterList: typeof import('./components/organism/CharacterList.vue')['default']
    'Fa:search': typeof import('~icons/fa/search')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Input: typeof import('./components/atoms/input/Input.vue')['default']
    Navbar: typeof import('./components/templates/layout/Navbar.vue')['default']
    Search: typeof import('./components/molecules/textfield/Search.vue')['default']
    Status: typeof import('./components/atoms/status/Status.vue')['default']
    Tabs: typeof import('./components/molecules/tabs/Tabs.vue')['default']
    Textfield: typeof import('./components/molecules/textfield/Textfield.vue')['default']
    TextfieldPassword: typeof import('./components/molecules/textfield/TextfieldPassword.vue')['default']
    'Zmdi:favorite': typeof import('~icons/zmdi/favorite')['default']
  }
}

export { }
